In [2]:
import pandas as pd
import numpy as np

In [5]:
df_in=pd.read_csv('C:\Users\AG28744\Desktop\Projects\Misc\DS_Datasets\healthcare-provider-fraud-detection-analysis\Train_Inpatientdata-1542865627584.csv')

In [6]:
df_in.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,...,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000,PHY390922,NaN,NaN,2009-04-12,...,2724,19889,5849,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BENE11001,CLM66048,2009-08-31,2009-09-02,PRV55907,5000,PHY318495,PHY318495,NaN,2009-08-31,...,NaN,NaN,NaN,NaN,7092.0,NaN,NaN,NaN,NaN,NaN
2,BENE11001,CLM68358,2009-09-17,2009-09-20,PRV56046,5000,PHY372395,NaN,PHY324689,2009-09-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BENE11011,CLM38412,2009-02-14,2009-02-22,PRV52405,5000,PHY369659,PHY392961,PHY349768,2009-02-14,...,25062,40390,4019,NaN,331.0,NaN,NaN,NaN,NaN,NaN
4,BENE11014,CLM63689,2009-08-13,2009-08-30,PRV56614,10000,PHY379376,PHY398258,NaN,2009-08-13,...,5119,29620,20300,NaN,3893.0,NaN,NaN,NaN,NaN,NaN

In [8]:
df_bene=pd.read_csv('C:\Users\AG28744\Desktop\Projects\Misc\DS_Datasets\healthcare-provider-fraud-detection-analysis\Train_Beneficiarydata-1542865627584.csv')
df_out=pd.read_csv('C:\Users\AG28744\Desktop\Projects\Misc\DS_Datasets\healthcare-provider-fraud-detection-analysis\Train_Outpatientdata-1542865627584.csv')
df_op=pd.read_csv('C:\Users\AG28744\Desktop\Projects\Misc\DS_Datasets\healthcare-provider-fraud-detection-analysis\Train-1542865627584.csv')

In [9]:
df_op.head()

   Provider PotentialFraud
0  PRV51001             No
1  PRV51003            Yes
2  PRV51004             No
3  PRV51005            Yes
4  PRV51007             No

In [6]:
from sklearn.preprocessing import LabelEncoder

In [11]:
# converting Yes=1, No=0

In [12]:
lb_make = LabelEncoder()
df_op['PotentialFraud']=lb_make.fit_transform(df_op['PotentialFraud'])
df_op.head()

   Provider  PotentialFraud
0  PRV51001               0
1  PRV51003               1
2  PRV51004               0
3  PRV51005               1
4  PRV51007               0

In [13]:
df_in.shape

(40474, 30)

In [14]:
df_bene.shape

(138556, 25)

In [15]:
bene_in=pd.merge(df_in, df_bene, how='left', on='BeneID')
bene_in.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000,PHY390922,NaN,NaN,2009-04-12,...,1,1,1,2,1,1,36000,3204,60,70
1,BENE11001,CLM66048,2009-08-31,2009-09-02,PRV55907,5000,PHY318495,PHY318495,NaN,2009-08-31,...,1,1,1,2,1,1,36000,3204,60,70
2,BENE11001,CLM68358,2009-09-17,2009-09-20,PRV56046,5000,PHY372395,NaN,PHY324689,2009-09-17,...,1,1,1,2,1,1,36000,3204,60,70
3,BENE11011,CLM38412,2009-02-14,2009-02-22,PRV52405,5000,PHY369659,PHY392961,PHY349768,2009-02-14,...,1,1,2,2,1,1,5000,1068,250,320
4,BENE11014,CLM63689,2009-08-13,2009-08-30,PRV56614,10000,PHY379376,PHY398258,NaN,2009-08-13,...,1,2,1,2,2,2,21260,2136,120,100

In [16]:
bene_in.shape

(40474, 54)

In [17]:
#export_bene_in_csv = bene_in.to_csv (r'C:\Users\AG28744\Desktop\Projects\Misc\DS_Datasets\healthcare-provider-fraud-detection-analysis\export_bene_in.csv', index = None, header=True)

In [18]:
bene_in_prov=pd.merge(bene_in, df_op, how='left', on='Provider')
bene_in_prov.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,...,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt,PotentialFraud
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000,PHY390922,NaN,NaN,2009-04-12,...,1,1,2,1,1,36000,3204,60,70,1
1,BENE11001,CLM66048,2009-08-31,2009-09-02,PRV55907,5000,PHY318495,PHY318495,NaN,2009-08-31,...,1,1,2,1,1,36000,3204,60,70,0
2,BENE11001,CLM68358,2009-09-17,2009-09-20,PRV56046,5000,PHY372395,NaN,PHY324689,2009-09-17,...,1,1,2,1,1,36000,3204,60,70,0
3,BENE11011,CLM38412,2009-02-14,2009-02-22,PRV52405,5000,PHY369659,PHY392961,PHY349768,2009-02-14,...,1,2,2,1,1,5000,1068,250,320,0
4,BENE11014,CLM63689,2009-08-13,2009-08-30,PRV56614,10000,PHY379376,PHY398258,NaN,2009-08-13,...,2,1,2,2,2,21260,2136,120,100,0

In [19]:
#export_bene_in_prov_csv = bene_in_prov.to_csv (r'C:\Users\AG28744\Desktop\Projects\Misc\DS_Datasets\healthcare-provider-fraud-detection-analysis\export_bene_in_prov.csv', index = None, header=True)

In [219]:
variables=['BeneID','ClaimID','ClaimStartDt','ClaimEndDt','InscClaimAmtReimbursed','AttendingPhysician','OperatingPhysician','OtherPhysician','AdmissionDt','DeductibleAmtPaid','DischargeDt','DOB','DOD',
'Race','State','County','NoOfMonths_PartACov','NoOfMonths_PartBCov','IPAnnualReimbursementAmt','IPAnnualDeductibleAmt','OPAnnualReimbursementAmt','OPAnnualDeductibleAmt']

In [130]:
fina_data_in=bene_in_prov.drop(variables, axis=1)
fina_data_in.shape

(40474, 33)

In [131]:
fina_data_in.columns.values

array(['Provider', 'ClmAdmitDiagnosisCode', 'DiagnosisGroupCode',
       'ClmDiagnosisCode_1', 'ClmDiagnosisCode_2', 'ClmDiagnosisCode_3',
       'ClmDiagnosisCode_4', 'ClmDiagnosisCode_5', 'ClmDiagnosisCode_6',
       'ClmDiagnosisCode_7', 'ClmDiagnosisCode_8', 'ClmDiagnosisCode_9',
       'ClmDiagnosisCode_10', 'ClmProcedureCode_1', 'ClmProcedureCode_2',
       'ClmProcedureCode_3', 'ClmProcedureCode_4', 'ClmProcedureCode_5',
       'ClmProcedureCode_6', 'Gender', 'RenalDiseaseIndicator',
       'ChronicCond_Alzheimer', 'ChronicCond_Heartfailure',
       'ChronicCond_KidneyDisease', 'ChronicCond_Cancer',
       'ChronicCond_ObstrPulmonary', 'ChronicCond_Depression',
       'ChronicCond_Diabetes', 'ChronicCond_IschemicHeart',
       'ChronicCond_Osteoporasis', 'ChronicCond_rheumatoidarthritis',
       'ChronicCond_stroke', 'PotentialFraud'], dtype=object)

In [132]:
fina_data_in['RenalDiseaseIndicator']=fina_data_in['RenalDiseaseIndicator'].replace('Y',1)

In [133]:
fina_data_in.RenalDiseaseIndicator.head()

0    0
1    0
2    0
3    0
4    1
Name: RenalDiseaseIndicator, dtype: object

In [134]:
fina_data_in.head()

,Provider,ClmAdmitDiagnosisCode,DiagnosisGroupCode,ClmDiagnosisCode_1,ClmDiagnosisCode_2,ClmDiagnosisCode_3,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,...,ChronicCond_KidneyDisease,ChronicCond_Cancer,ChronicCond_ObstrPulmonary,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,PotentialFraud
0,PRV55912,7866,201,1970,4019,5853,7843,2768,71590,2724,...,1,2,2,1,1,1,2,1,1,1
1,PRV55907,6186,750,6186,2948,56400,NaN,NaN,NaN,NaN,...,1,2,2,1,1,1,2,1,1,0
2,PRV56046,29590,883,29623,30390,71690,34590,V1581,32723,NaN,...,1,2,2,1,1,1,2,1,1,0
3,PRV52405,431,067,43491,2762,7843,32723,V1041,4254,25062,...,1,2,2,1,1,2,2,1,1,0
4,PRV56614,78321,975,042,3051,34400,5856,42732,486,5119,...,1,2,1,1,2,1,2,2,2,0

In [84]:
#df[cols]=df[cols].fillna(0)  or df.loc[:,'a':'c'] = df.loc[:,'a':'c'].fillna(0)

In [27]:
cols=['Provider', 'ClmAdmitDiagnosisCode', 'DiagnosisGroupCode',
 'ClmDiagnosisCode_1', 'ClmDiagnosisCode_2', 'ClmDiagnosisCode_3',
 'ClmDiagnosisCode_4', 'ClmDiagnosisCode_5', 'ClmDiagnosisCode_6',
 'ClmDiagnosisCode_7', 'ClmDiagnosisCode_8', 'ClmDiagnosisCode_9',
 'ClmDiagnosisCode_10', 'ClmProcedureCode_1', 'ClmProcedureCode_2',
 'ClmProcedureCode_3', 'ClmProcedureCode_4', 'ClmProcedureCode_5',
 'ClmProcedureCode_6', 'Gender', 'RenalDiseaseIndicator',
 'ChronicCond_Alzheimer', 'ChronicCond_Heartfailure',
 'ChronicCond_KidneyDisease', 'ChronicCond_Cancer',
 'ChronicCond_ObstrPulmonary', 'ChronicCond_Depression',
 'ChronicCond_Diabetes', 'ChronicCond_IschemicHeart',
 'ChronicCond_Osteoporasis', 'ChronicCond_rheumatoidarthritis',
 'ChronicCond_stroke', 'PotentialFraud']

In [154]:
fina_data_in[cols]=fina_data_in[cols].fillna(0)   #filling all na wth 0

In [88]:
#res=fina_data_in.DiagnosisGroupCode.split()

In [89]:
#x = open("DiagnosisGroupCode.txt","w+")

In [34]:
#for i in fina_data_in.DiagnosisGroupCode:
#    x.write(str(i))
#    x.write("\n")

In [35]:
#x.close()

In [36]:
#x = open("DiagnosisGroupCode.txt","r")

In [37]:
#contents=pd.read_table('DiagnosisGroupCode.txt',names=('A'))

In [38]:
#contents.head()

In [39]:
#import re
#col = str(contents.A)
#x_DiagnosisGroupCode = re.sub("\AO", "1000", col)

In [40]:
#fina_data_in['DiagnosisGroupCode1']=x_DiagnosisGroupCode

In [41]:
#export_contents_csv = fina_data_in.to_csv (r'C:\Users\AG28744\Desktop\Projects\Misc\DS_Datasets\healthcare-provider-fraud-detection-analysis\export_fina_data_in2.csv', index = None, header=True)

In [42]:
#import re

#z = re.search('[a-zA-Z]', col)
#print(z)

In [126]:
#data = fina_data_in.set_index("DiagnosisGroupCode")
#data.head()
#x_DiagnosisGroupCode=pd.DataFrame(data)

In [137]:
# To delete rows with OTH
#x_DiagnosisGroupCode_index = fina_data_in[fina_data_in['DiagnosisGroupCode']=='OTH'].index
#x=fina_data_in.drop(x_DiagnosisGroupCode_index, inplace = True) 
#print(x)

In [138]:
#x=pd.DataFrame(x)
#x.head()
#print(x)

In [156]:
export_contents_csv = fina_data_in.to_csv (r'C:\Users\AG28744\Desktop\Projects\Misc\DS_Datasets\healthcare-provider-fraud-detection-analysis\fina_data_in2.csv', index = None, header=True)

In [172]:
#x = fina_data_in[pd.to_numeric(fina_data_in['DiagnosisGroupCode'], errors='coerce').isnull()]

In [173]:
#y = fina_data_in.index(fina_data_in['ClmDiagnosisCode_2'].str.contains("V4571"))

In [60]:
train_final_data=pd.read_csv('C:\Users\AG28744\Desktop\Projects\Misc\DS_Datasets\healthcare-provider-fraud-detection-analysis\Final_train2.csv')
train_final_data.head()

,Provider,ClmAdmitDiagnosisCode,DiagnosisGroupCode,ClmDiagnosisCode_1,ClmDiagnosisCode_2,ClmDiagnosisCode_3,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,...,ChronicCond_KidneyDisease,ChronicCond_Cancer,ChronicCond_ObstrPulmonary,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,PotentialFraud
0,PRV55912,7866,201,1970,4019,5853,7843,2768,71590,2724,...,1,2,2,1,1,1,2,1,1,1
1,PRV55907,6186,750,6186,2948,56400,0,0,0,0,...,1,2,2,1,1,1,2,1,1,0
2,PRV56614,78321,975,42,3051,34400,5856,42732,486,5119,...,1,2,1,1,2,1,2,2,2,0
3,PRV54090,5699,390,1536,73300,7230,3659,2859,4019,2948,...,2,1,2,2,2,1,1,1,2,0
4,PRV51148,78605,379,56212,25000,30000,73300,2766,53081,2851,...,2,2,2,2,1,1,1,2,2,1

In [61]:
train_final_data.shape

(17560, 33)

In [30]:
train_final_data.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
ClmAdmitDiagnosisCode,17560.0,38033.733371,33120.493196,30.0,5693.00,34590.0,78079.00,99939.0
DiagnosisGroupCode,17560.0,423.518565,260.664995,0.0,217.00,343.0,641.00,999.0
ClmDiagnosisCode_1,17560.0,29518.701822,28011.111700,30.0,4358.00,27651.0,49121.00,99989.0
ClmDiagnosisCode_2,17560.0,22860.200513,25679.480246,0.0,3310.00,5939.0,41401.00,99939.0
ClmDiagnosisCode_3,17560.0,22245.136503,25577.090291,0.0,2948.00,5856.0,41400.00,99931.0
ClmDiagnosisCode_4,17560.0,21475.604841,25548.366194,0.0,2851.00,5849.0,41400.00,99989.0
ClmDiagnosisCode_5,17560.0,20719.565034,25610.115130,0.0,2746.75,5601.0,40391.00,99989.0
ClmDiagnosisCode_6,17560.0,18825.251196,24869.172720,0.0,2446.25,4538.0,34831.00,99939.0
ClmDiagnosisCode_7,17560.0,17623.228474,24659.175831,0.0,311.00,4241.0,30411.00,99931.0
ClmDiagnosisCode_8,17560.0,16463.829100,24577.439856,0.0,0.00,4019.0,28884.75,99989.0
ClmDiagnosisCode_9,17560.0,14293.738041,23332.586608,0.0,0.00,2768.0,25000.00,99989.0
ClmDiagnosisCode_10,17560.0,1812.830581,9807.483776,0.0,0.00,0.0,0.00,99931.0
ClmProcedureCode_1,17560.0,3339.646640,3689.375271,0.0,0.00,3324.0,6029.00,9999.0
ClmProcedureCode_2,17560.0,556.044875,1613.032013,0.0,0.00,0.0,0.00,9999.0
ClmProcedureCode_3,17560.0,102.553986,757.415618,0.0,0.00,0.0,0.00,9982.0
ClmProcedureCode_4,17560.0,10.355923,229.741312,0.0,0.00,0.0,0.00,9986.0
ClmProcedureCode_5,17560.0,0.958656,84.020302,0.0,0.00,0.0,0.00,9971.0
ClmProcedureCode_6,17560.0,0.000000,0.000000,0.0,0.00,0.0,0.00,0.0
Gender,17560.0,1.572380,0.494747,1.0,1.00,2.0,2.00,2.0
RenalDiseaseIndicator,17560.0,0.273918,0.445980,0.0,0.00,0.0,1.00,1.0
ChronicCond_Alzheimer,17560.0,1.483827,0.499753,1.0,1.00,1.0,2.00,2.0
ChronicCond_Heartfailure,17560.0,1.266515,0.442149,1.0,1.00,1.0,2.00,2.0
ChronicCond_KidneyDisease,17560.0,1.372153,0.483393,1.0,1.00,1.0,2.00,2.0
ChronicCond_Cancer,17560.0,1.807062,0.394616,1.0,2.00,2.0,2.00,2.0
ChronicCond_ObstrPulmonary,17560.0,1.510137,0.499911,1.0,1.00,2.0,2.00,2.0
ChronicCond_Depression,17560.0,1.499032,0.500013,1.0,1.00,1.0,2.00,2.0
ChronicCond_Diabetes,17560.0,1.200057,0.400054,1.0,1.00,1.0,1.00,2.0
ChronicCond_IschemicHeart,17560.0,1.144305,0.351409,1.0,1.00,1.0,1.00,2.0
ChronicCond_Osteoporasis,17560.0,1.650854,0.476714,1.0,1.00,2.0,2.00,2.0
ChronicCond_rheumatoidarthritis,17560.0,1.650000,0.476983,1.0,1.00,2.0,2.00,2.0
ChronicCond_stroke,17560.0,1.824260,0.380610,1.0,2.00,2.0,2.00,2.0
PotentialFraud,17560.0,0.577392,0.493988,0.0,0.00,1.0,1.00,1.0

In [62]:
train_predictors = train_final_data[train_final_data.columns[1:32]]
train_predictors.head()

,ClmAdmitDiagnosisCode,DiagnosisGroupCode,ClmDiagnosisCode_1,ClmDiagnosisCode_2,ClmDiagnosisCode_3,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,ClmDiagnosisCode_8,...,ChronicCond_Heartfailure,ChronicCond_KidneyDisease,ChronicCond_Cancer,ChronicCond_ObstrPulmonary,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke
0,7866,201,1970,4019,5853,7843,2768,71590,2724,19889,...,2,1,2,2,1,1,1,2,1,1
1,6186,750,6186,2948,56400,0,0,0,0,0,...,2,1,2,2,1,1,1,2,1,1
2,78321,975,42,3051,34400,5856,42732,486,5119,29620,...,1,1,2,1,1,2,1,2,2,2
3,5699,390,1536,73300,7230,3659,2859,4019,2948,2809,...,1,2,1,2,2,2,1,1,1,2
4,78605,379,56212,25000,30000,73300,2766,53081,2851,4439,...,2,2,2,2,2,1,1,1,2,2

In [63]:
from sklearn import preprocessing

In [64]:
train_predictors=preprocessing.scale(train_predictors)
train_predictors=pd.DataFrame(train_predictors)
train_predictors.head()

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
0,-0.910874,-0.853682,-0.983520,-0.733727,-0.640910,-0.533615,-0.700976,2.121753,-0.604223,0.139366,...,1.658957,-0.769899,0.488941,0.979928,-0.998066,-0.500089,-0.410659,0.732422,-1.362770,-2.165690
1,-0.961599,1.252530,-0.833004,-0.775435,1.335407,-0.840610,-0.809061,-0.756993,-0.714693,-0.669895,...,1.658957,-0.769899,0.488941,0.979928,-0.998066,-0.500089,-0.410659,0.732422,-1.362770,-2.165690
2,1.216420,2.115731,-1.052352,-0.771424,0.475238,-0.611391,0.859546,-0.737450,-0.507097,0.535310,...,-0.602789,-0.769899,0.488941,-1.020483,-0.998066,1.999644,-0.410659,0.732422,0.733799,0.461747
3,-0.976304,-0.128592,-0.999014,1.964262,-0.587071,-0.697388,-0.697423,-0.595383,-0.595139,-0.555600,...,-0.602789,1.298872,-2.045238,0.979928,1.001938,1.999644,-0.410659,-1.365333,-1.362770,0.461747
4,1.224994,-0.170793,0.952981,0.083330,0.303204,2.028540,-0.701054,1.377477,-0.599073,-0.489277,...,1.658957,1.298872,0.488941,0.979928,1.001938,-0.500089,-0.410659,-1.365333,0.733799,0.461747

In [65]:
train_target=train_final_data[['PotentialFraud']]

In [66]:
from sklearn.tree import DecisionTreeClassifier

In [67]:
model=DecisionTreeClassifier(criterion='entropy')

In [68]:
model.fit(train_predictors,train_target)   #DecisionTree model

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [69]:
preds_train=model.predict(train_predictors)
preds_train=pd.DataFrame(preds_train)
preds_train.head()

   0
0  1
1  0
2  0
3  0
4  1

In [70]:
train_final_data['preds_train']=preds_train
train_final_data.head()

,Provider,ClmAdmitDiagnosisCode,DiagnosisGroupCode,ClmDiagnosisCode_1,ClmDiagnosisCode_2,ClmDiagnosisCode_3,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,...,ChronicCond_Cancer,ChronicCond_ObstrPulmonary,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,PotentialFraud,preds_train
0,PRV55912,7866,201,1970,4019,5853,7843,2768,71590,2724,...,2,2,1,1,1,2,1,1,1,1
1,PRV55907,6186,750,6186,2948,56400,0,0,0,0,...,2,2,1,1,1,2,1,1,0,0
2,PRV56614,78321,975,42,3051,34400,5856,42732,486,5119,...,2,1,1,2,1,2,2,2,0,0
3,PRV54090,5699,390,1536,73300,7230,3659,2859,4019,2948,...,1,2,2,2,1,1,1,2,0,0
4,PRV51148,78605,379,56212,25000,30000,73300,2766,53081,2851,...,2,2,2,1,1,1,2,2,1,1

In [71]:
from sklearn.metrics import confusion_matrix

In [72]:
confusion_matrix(train_final_data.PotentialFraud,preds_train)

array([[ 7421,     0],
       [    0, 10139]], dtype=int64)

In [215]:
df_in_test=pd.read_csv('C:\Users\AG28744\Desktop\Projects\Misc\DS_Datasets\healthcare-provider-fraud-detection-analysis\Test_Inpatientdata-1542969243754.csv')
df_in_test.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,...,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6
0,BENE11014,CLM67387,2009-09-09,2009-09-16,PRV57070,9000,PHY317786,PHY427017,NaN,2009-09-09,...,5990,570,41071,4280,4443.0,5849.0,NaN,NaN,NaN,NaN
1,BENE11017,CLM31237,2008-12-25,2009-01-08,PRV54750,14000,PHY314656,PHY426644,NaN,2008-12-25,...,4549,29570,34831,NaN,5551.0,NaN,NaN,NaN,NaN,NaN
2,BENE11026,CLM78930,2009-12-09,2009-12-13,PRV53758,2000,PHY349495,NaN,NaN,2009-12-09,...,78650,7813,4254,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BENE11031,CLM56810,2009-06-23,2009-07-06,PRV55825,16000,PHY429538,PHY371893,NaN,2009-06-23,...,4254,41400,5849,41401,8152.0,3320.0,NaN,NaN,NaN,NaN
4,BENE11085,CLM34625,2009-01-20,2009-01-31,PRV52338,19000,PHY397161,NaN,NaN,2009-01-20,...,V6109,7242,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [225]:
df_bene_test=pd.read_csv('C:\Users\AG28744\Desktop\Projects\Misc\DS_Datasets\healthcare-provider-fraud-detection-analysis\Test_Beneficiarydata-1542969243754.csv')
df_op_test=pd.read_csv('C:\Users\AG28744\Desktop\Projects\Misc\DS_Datasets\healthcare-provider-fraud-detection-analysis\Test-1542969243754.csv')
df_op_test.head()

   Provider
0  PRV51002
1  PRV51006
2  PRV51009
3  PRV51010
4  PRV51018

In [226]:
bene_in_test=pd.merge(df_in_test, df_bene_test, how='left', on='BeneID')
bene_in_test.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
0,BENE11014,CLM67387,2009-09-09,2009-09-16,PRV57070,9000,PHY317786,PHY427017,NaN,2009-09-09,...,1,2,1,2,2,2,21260,2136,120,100
1,BENE11017,CLM31237,2008-12-25,2009-01-08,PRV54750,14000,PHY314656,PHY426644,NaN,2008-12-25,...,2,1,1,2,1,1,22000,2136,1400,840
2,BENE11026,CLM78930,2009-12-09,2009-12-13,PRV53758,2000,PHY349495,NaN,NaN,2009-12-09,...,2,2,1,2,2,2,2000,1068,0,0
3,BENE11031,CLM56810,2009-06-23,2009-07-06,PRV55825,16000,PHY429538,PHY371893,NaN,2009-06-23,...,2,2,1,1,2,2,23650,2136,40,0
4,BENE11085,CLM34625,2009-01-20,2009-01-31,PRV52338,19000,PHY397161,NaN,NaN,2009-01-20,...,1,1,1,1,2,2,19000,1068,1670,520

In [227]:
bene_in_prov_test=pd.merge(bene_in_test, df_op_test, how='left', on='Provider')
bene_in_prov_test.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
0,BENE11014,CLM67387,2009-09-09,2009-09-16,PRV57070,9000,PHY317786,PHY427017,NaN,2009-09-09,...,1,2,1,2,2,2,21260,2136,120,100
1,BENE11017,CLM31237,2008-12-25,2009-01-08,PRV54750,14000,PHY314656,PHY426644,NaN,2008-12-25,...,2,1,1,2,1,1,22000,2136,1400,840
2,BENE11026,CLM78930,2009-12-09,2009-12-13,PRV53758,2000,PHY349495,NaN,NaN,2009-12-09,...,2,2,1,2,2,2,2000,1068,0,0
3,BENE11031,CLM56810,2009-06-23,2009-07-06,PRV55825,16000,PHY429538,PHY371893,NaN,2009-06-23,...,2,2,1,1,2,2,23650,2136,40,0
4,BENE11085,CLM34625,2009-01-20,2009-01-31,PRV52338,19000,PHY397161,NaN,NaN,2009-01-20,...,1,1,1,1,2,2,19000,1068,1670,520

In [228]:
bene_in_prov.columns.values

array(['BeneID', 'ClaimID', 'ClaimStartDt', 'ClaimEndDt', 'Provider',
       'InscClaimAmtReimbursed', 'AttendingPhysician',
       'OperatingPhysician', 'OtherPhysician', 'AdmissionDt',
       'ClmAdmitDiagnosisCode', 'DeductibleAmtPaid', 'DischargeDt',
       'DiagnosisGroupCode', 'ClmDiagnosisCode_1', 'ClmDiagnosisCode_2',
       'ClmDiagnosisCode_3', 'ClmDiagnosisCode_4', 'ClmDiagnosisCode_5',
       'ClmDiagnosisCode_6', 'ClmDiagnosisCode_7', 'ClmDiagnosisCode_8',
       'ClmDiagnosisCode_9', 'ClmDiagnosisCode_10', 'ClmProcedureCode_1',
       'ClmProcedureCode_2', 'ClmProcedureCode_3', 'ClmProcedureCode_4',
       'ClmProcedureCode_5', 'ClmProcedureCode_6', 'DOB', 'DOD', 'Gender',
       'Race', 'RenalDiseaseIndicator', 'State', 'County',
       'NoOfMonths_PartACov', 'NoOfMonths_PartBCov',
       'ChronicCond_Alzheimer', 'ChronicCond_Heartfailure',
       'ChronicCond_KidneyDisease', 'ChronicCond_Cancer',
       'ChronicCond_ObstrPulmonary', 'ChronicCond_Depression',
       'ChronicCond_Diabetes', 'ChronicCond_IschemicHeart',
       'ChronicCond_Osteoporasis', 'ChronicCond_rheumatoidarthritis',
       'ChronicCond_stroke', 'IPAnnualReimbursementAmt',
       'IPAnnualDeductibleAmt', 'OPAnnualReimbursementAmt',
       'OPAnnualDeductibleAmt', 'PotentialFraud'], dtype=object)

In [229]:
final_data_in_test=bene_in_prov_test.drop(variables, axis=1)
final_data_in_test.shape

(9551, 32)

In [230]:
final_data_in_test.columns.values

array(['Provider', 'ClmAdmitDiagnosisCode', 'DiagnosisGroupCode',
       'ClmDiagnosisCode_1', 'ClmDiagnosisCode_2', 'ClmDiagnosisCode_3',
       'ClmDiagnosisCode_4', 'ClmDiagnosisCode_5', 'ClmDiagnosisCode_6',
       'ClmDiagnosisCode_7', 'ClmDiagnosisCode_8', 'ClmDiagnosisCode_9',
       'ClmDiagnosisCode_10', 'ClmProcedureCode_1', 'ClmProcedureCode_2',
       'ClmProcedureCode_3', 'ClmProcedureCode_4', 'ClmProcedureCode_5',
       'ClmProcedureCode_6', 'Gender', 'RenalDiseaseIndicator',
       'ChronicCond_Alzheimer', 'ChronicCond_Heartfailure',
       'ChronicCond_KidneyDisease', 'ChronicCond_Cancer',
       'ChronicCond_ObstrPulmonary', 'ChronicCond_Depression',
       'ChronicCond_Diabetes', 'ChronicCond_IschemicHeart',
       'ChronicCond_Osteoporasis', 'ChronicCond_rheumatoidarthritis',
       'ChronicCond_stroke'], dtype=object)

In [231]:
final_data_in_test.head()

,Provider,ClmAdmitDiagnosisCode,DiagnosisGroupCode,ClmDiagnosisCode_1,ClmDiagnosisCode_2,ClmDiagnosisCode_3,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,...,ChronicCond_Heartfailure,ChronicCond_KidneyDisease,ChronicCond_Cancer,ChronicCond_ObstrPulmonary,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke
0,PRV57070,5789,332,5780,5533,496,V420,40390,2851,5990,...,1,1,2,1,1,2,1,2,2,2
1,PRV54750,5939,661,1889,41071,5990,5601,4588,5845,4549,...,1,1,1,1,2,1,1,2,1,1
2,PRV53758,4019,241,4010,78791,60000,41401,V1254,4372,78650,...,2,2,2,2,2,2,1,2,2,2
3,PRV55825,8208,564,8208,4168,920,5990,40391,2859,4254,...,1,1,2,2,2,2,1,1,2,2
4,PRV52338,4279,880,29654,V142,78702,30503,V140,V4582,V6109,...,1,1,1,1,1,1,1,1,2,2

In [233]:
cols_test=['Provider', 'ClmAdmitDiagnosisCode', 'DiagnosisGroupCode',
 'ClmDiagnosisCode_1', 'ClmDiagnosisCode_2', 'ClmDiagnosisCode_3',
 'ClmDiagnosisCode_4', 'ClmDiagnosisCode_5', 'ClmDiagnosisCode_6',
 'ClmDiagnosisCode_7', 'ClmDiagnosisCode_8', 'ClmDiagnosisCode_9',
 'ClmDiagnosisCode_10', 'ClmProcedureCode_1', 'ClmProcedureCode_2',
 'ClmProcedureCode_3', 'ClmProcedureCode_4', 'ClmProcedureCode_5',
 'ClmProcedureCode_6', 'Gender', 'RenalDiseaseIndicator',
 'ChronicCond_Alzheimer', 'ChronicCond_Heartfailure',
 'ChronicCond_KidneyDisease', 'ChronicCond_Cancer',
 'ChronicCond_ObstrPulmonary', 'ChronicCond_Depression',
 'ChronicCond_Diabetes', 'ChronicCond_IschemicHeart',
 'ChronicCond_Osteoporasis', 'ChronicCond_rheumatoidarthritis',
 'ChronicCond_stroke']

In [234]:
final_data_in_test[cols_test]=final_data_in_test[cols_test].fillna(0)

In [235]:
export_final_data_in_test_csv = final_data_in_test.to_csv(r'C:\Users\AG28744\Desktop\Projects\Misc\DS_Datasets\healthcare-provider-fraud-detection-analysis\final_data_in_test.csv', index = None, header=True)

In [53]:
test=pd.read_csv(r'C:\Users\AG28744\Desktop\Projects\Misc\DS_Datasets\healthcare-provider-fraud-detection-analysis\test.csv',encoding='utf-8')

In [54]:
test['RenalDiseaseIndicator']=test['RenalDiseaseIndicator'].replace('Y',1)
test.head()

,Provider,ClmAdmitDiagnosisCode,DiagnosisGroupCode,ClmDiagnosisCode_1,ClmDiagnosisCode_2,ClmDiagnosisCode_3,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,...,ChronicCond_Heartfailure,ChronicCond_KidneyDisease,ChronicCond_Cancer,ChronicCond_ObstrPulmonary,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke
0,PRV54750,5939,661,1889,41071,5990,5601,4588,5845,4549,...,1,1,1,1,2,1,1,2,1,1
1,PRV55825,8208,564,8208,4168,920,5990,40391,2859,4254,...,1,1,2,2,2,2,1,1,2,2
2,PRV57214,389,853,389,51881,2752,5849,42731,53540,2760,...,1,1,2,2,2,2,1,2,2,2
3,PRV55190,4359,32,43491,42769,53081,496,2720,41401,3659,...,2,2,2,1,2,1,1,1,2,1
4,PRV54853,99649,479,7140,25000,0,0,0,0,0,...,1,1,2,1,1,1,1,2,1,2

In [73]:
test_data=test[test.columns[1:32]]
test_data=preprocessing.scale(test_data)
test_data=pd.DataFrame(test_data)
test_data.head()

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
0,-0.995434,0.928435,-0.986696,0.693812,-0.632233,-0.609117,-0.618676,-0.530637,-0.535623,0.516747,...,-0.621063,-0.781626,-2.064855,-1.038546,1.004586,-0.520766,-0.420104,0.737084,-1.352412,-2.183588
1,-0.926454,0.558165,-0.760882,-0.722884,-0.827661,-0.594186,0.799421,-0.646989,-0.547501,0.997941,...,-0.621063,-0.781626,0.484296,0.962884,1.004586,1.920250,-0.420104,-1.356698,0.739419,0.457962
2,-1.164161,1.661342,-1.040300,1.108805,-0.757045,-0.599598,0.892105,1.327835,-0.607655,-0.666267,...,-0.621063,-0.781626,0.484296,0.962884,1.004586,1.920250,-0.420104,0.737084,0.739419,0.457962
3,-1.043468,-1.472598,0.499983,0.758997,1.182935,-0.805056,-0.692665,0.854830,-0.571458,-0.586421,...,1.610143,1.279385,0.484296,-1.038546,1.004586,-0.520766,-0.420104,-1.356698,0.739419,-2.183588
4,1.853473,0.233701,-0.799048,0.076850,-0.863123,-0.824093,-0.800399,-0.758392,-0.718783,-0.686036,...,-0.621063,-0.781626,0.484296,-1.038546,-0.995435,-0.520766,-0.420104,0.737084,-1.352412,0.457962

In [74]:
preds=model.predict(test_data)

In [75]:
test['predicted_fraud']=preds
test.head()

,Provider,ClmAdmitDiagnosisCode,DiagnosisGroupCode,ClmDiagnosisCode_1,ClmDiagnosisCode_2,ClmDiagnosisCode_3,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,...,ChronicCond_KidneyDisease,ChronicCond_Cancer,ChronicCond_ObstrPulmonary,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,predicted_fraud
0,PRV54750,5939,661,1889,41071,5990,5601,4588,5845,4549,...,1,1,1,2,1,1,2,1,1,0
1,PRV55825,8208,564,8208,4168,920,5990,40391,2859,4254,...,1,2,2,2,2,1,1,2,2,1
2,PRV57214,389,853,389,51881,2752,5849,42731,53540,2760,...,1,2,2,2,2,1,2,2,2,0
3,PRV55190,4359,32,43491,42769,53081,496,2720,41401,3659,...,2,2,1,2,1,1,1,2,1,0
4,PRV54853,99649,479,7140,25000,0,0,0,0,0,...,1,2,1,1,1,1,2,1,2,0

In [76]:
test=test[['ClmAdmitDiagnosisCode', 'DiagnosisGroupCode',
 'ClmDiagnosisCode_1', 'ClmDiagnosisCode_2', 'ClmDiagnosisCode_3',
 'ClmDiagnosisCode_4', 'ClmDiagnosisCode_5', 'ClmDiagnosisCode_6',
 'ClmDiagnosisCode_7', 'ClmDiagnosisCode_8', 'ClmDiagnosisCode_9',
 'ClmDiagnosisCode_10', 'ClmProcedureCode_1', 'ClmProcedureCode_2',
 'ClmProcedureCode_3', 'ClmProcedureCode_4', 'ClmProcedureCode_5',
 'ClmProcedureCode_6', 'Gender', 'RenalDiseaseIndicator',
 'ChronicCond_Alzheimer', 'ChronicCond_Heartfailure',
 'ChronicCond_KidneyDisease', 'ChronicCond_Cancer',
 'ChronicCond_ObstrPulmonary', 'ChronicCond_Depression',
 'ChronicCond_Diabetes', 'ChronicCond_IschemicHeart',
 'ChronicCond_Osteoporasis', 'ChronicCond_rheumatoidarthritis',
 'ChronicCond_stroke','Provider','predicted_fraud']]

In [77]:
 predicted_fraud= test.to_csv(r'C:\Users\AG28744\Desktop\Projects\Misc\DS_Datasets\healthcare-provider-fraud-detection-analysis\predicted_fraud.csv', index = None, header=True)